table! {
    use diesel::sql_types::*;

    /// Representation of the `account` table.
    ///
    /// (Automatically generated by Diesel.)
    account (id) {
        /// The `id` column of the `account` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `client_id` column of the `account` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `role_id` column of the `account` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        role_id -> Int8,
        /// The `avatar` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        avatar -> Nullable<Text>,
        /// The `prefix` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        prefix -> Nullable<Varchar>,
        /// The `first_name` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        first_name -> Nullable<Varchar>,
        /// The `middle_name` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        middle_name -> Nullable<Varchar>,
        /// The `last_name` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        last_name -> Nullable<Varchar>,
        /// The `suffix` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        suffix -> Nullable<Varchar>,
        /// The `pwd_hash` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        pwd_hash -> Nullable<Varchar>,
        /// The `email` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Varchar>,
        /// The `email_verified` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        email_verified -> Nullable<Bool>,
        /// The `phone_number` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        phone_number -> Nullable<Varchar>,
        /// The `topt_secret` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        topt_secret -> Nullable<Varchar>,
        /// The `mfa_enabled` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        mfa_enabled -> Nullable<Bool>,
        /// The `self_password_reset` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        self_password_reset -> Nullable<Bool>,
        /// The `pwd_last_updated` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        pwd_last_updated -> Nullable<Timestamp>,
        /// The `enc_key` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        enc_key -> Nullable<Text>,
        /// The `notify_on_suspicious_login` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_suspicious_login -> Nullable<Bool>,
        /// The `notify_on_pwd_reset` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_pwd_reset -> Nullable<Bool>,
        /// The `notify_on_email_change` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_email_change -> Nullable<Bool>,
        /// The `notify_on_mfa_change` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_mfa_change -> Nullable<Bool>,
        /// The `notify_on_phone_number_change` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_phone_number_change -> Nullable<Bool>,
        /// The `notify_on_comment` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        notify_on_comment -> Nullable<Bool>,
        /// The `notification_frequency` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        notification_frequency -> Nullable<Varchar>,
        /// The `archived` column of the `account` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        archived -> Nullable<Bool>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `account_access_history` table.
    ///
    /// (Automatically generated by Diesel.)
    account_access_history (id) {
        /// The `id` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `client_id` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `session_id` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        session_id -> Nullable<Int8>,
        /// The `account_id` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        account_id -> Int8,
        /// The `ip` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Nullable<Varchar>,
        /// The `operating_system` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        operating_system -> Nullable<Varchar>,
        /// The `mobile` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        mobile -> Nullable<Bool>,
        /// The `platform` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        platform -> Nullable<Varchar>,
        /// The `engine_name` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        engine_name -> Nullable<Varchar>,
        /// The `engine_version` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        engine_version -> Nullable<Varchar>,
        /// The `browser_name` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        browser_name -> Nullable<Varchar>,
        /// The `browser_version` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        browser_version -> Nullable<Varchar>,
        /// The `localization` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        localization -> Nullable<Varchar>,
        /// The `country_code` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        country_code -> Nullable<Varchar>,
        /// The `region` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        region -> Nullable<Varchar>,
        /// The `city` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        city -> Nullable<Varchar>,
        /// The `latitude` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        latitude -> Nullable<Float8>,
        /// The `longitude` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        longitude -> Nullable<Float8>,
        /// The `login` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        login -> Nullable<Timestamp>,
        /// The `total_session` column of the `account_access_history` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        total_session -> Nullable<Int4>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `account_pwd_history` table.
    ///
    /// (Automatically generated by Diesel.)
    account_pwd_history (account_id, pwd) {
        /// The `account_id` column of the `account_pwd_history` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        account_id -> Int8,
        /// The `pwd` column of the `account_pwd_history` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        pwd -> Varchar,
        /// The `last_used_on` column of the `account_pwd_history` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_on -> Nullable<Timestamp>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `account_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    account_tokens (account_id, type_) {
        /// The `account_id` column of the `account_tokens` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        account_id -> Int8,
        /// The `type` column of the `account_tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "type"]
        type_ -> Varchar,
        /// The `token` column of the `account_tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Nullable<Varchar>,
        /// The `token_exp` column of the `account_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        token_exp -> Nullable<Timestamp>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `audit_log` table.
    ///
    /// (Automatically generated by Diesel.)
    audit_log (id) {
        /// The `id` column of the `audit_log` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `client_id` column of the `audit_log` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `entity_id` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        entity_id -> Nullable<Int8>,
        /// The `entity_type` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        entity_type -> Nullable<Varchar>,
        /// The `operation` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        operation -> Nullable<Varchar>,
        /// The `info` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        info -> Nullable<Text>,
        /// The `generated_on` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        generated_on -> Nullable<Timestamp>,
        /// The `generated_by` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        generated_by -> Nullable<Int8>,
        /// The `ip` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Nullable<Varchar>,
        /// The `country_code` column of the `audit_log` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        country_code -> Nullable<Varchar>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `client` table.
    ///
    /// (Automatically generated by Diesel.)
    client (id) {
        /// The `id` column of the `client` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `name` column of the `client` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `unique_id` column of the `client` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        unique_id -> Varchar,
        /// The `session_key` column of the `client` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        session_key -> Varchar,
        /// The `session_key_last_rotation` column of the `client` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        session_key_last_rotation -> Timestamp,
        /// The `enable_payload_encryption` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        enable_payload_encryption -> Nullable<Bool>,
        /// The `payload_encryption_key` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        payload_encryption_key -> Nullable<Text>,
        /// The `encryption_key` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        encryption_key -> Nullable<Text>,
        /// The `admin_email` column of the `client` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        admin_email -> Varchar,
        /// The `website` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        website -> Nullable<Varchar>,
        /// The `registered_on` column of the `client` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        registered_on -> Timestamp,
        /// The `expires_on` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_on -> Nullable<Timestamp>,
        /// The `welcome_template` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        welcome_template -> Nullable<Text>,
        /// The `min_pwd_len` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        min_pwd_len -> Nullable<Int4>,
        /// The `max_pwd_len` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_pwd_len -> Nullable<Int4>,
        /// The `numeric_chars` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        numeric_chars -> Nullable<Int4>,
        /// The `lowercase_chars` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        lowercase_chars -> Nullable<Int4>,
        /// The `uppercase_chars` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        uppercase_chars -> Nullable<Int4>,
        /// The `special_chars` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        special_chars -> Nullable<Int4>,
        /// The `special_char_set` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        special_char_set -> Nullable<Varchar>,
        /// The `require_email_validation` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        require_email_validation -> Nullable<Bool>,
        /// The `self_service_pwd_reset` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        self_service_pwd_reset -> Nullable<Bool>,
        /// The `pwd_reused` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        pwd_reused -> Nullable<Int4>,
        /// The `max_pwd_age` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_pwd_age -> Nullable<Int4>,
        /// The `enforce_mfa` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        enforce_mfa -> Nullable<Bool>,
        /// The `whitelist_cidrs` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        whitelist_cidrs -> Nullable<Array<Text>>,
        /// The `trusted_cidrs` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        trusted_cidrs -> Nullable<Array<Text>>,
        /// The `session_interval` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        session_interval -> Nullable<Varchar>,
        /// The `session_key_rotation` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        session_key_rotation -> Nullable<Int4>,
        /// The `data_key_rotation` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        data_key_rotation -> Nullable<Int4>,
        /// The `allow_username_reminder` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        allow_username_reminder -> Nullable<Bool>,
        /// The `allow_multiple_sessions` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        allow_multiple_sessions -> Nullable<Bool>,
        /// The `max_approval_wait_time` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        max_approval_wait_time -> Nullable<Varchar>,
        /// The `approval_duration` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        approval_duration -> Nullable<Varchar>,
        /// The `brute_force_protection` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        brute_force_protection -> Nullable<Bool>,
        /// The `suspicious_ip_limit` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        suspicious_ip_limit -> Nullable<Int4>,
        /// The `suspicious_ip_throttle` column of the `client` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        suspicious_ip_throttle -> Nullable<Varchar>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `country` table.
    ///
    /// (Automatically generated by Diesel.)
    country (id) {
        /// The `id` column of the `country` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `code` column of the `country` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Nullable<Varchar>,
        /// The `name` column of the `country` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `policy` table.
    ///
    /// (Automatically generated by Diesel.)
    policy (id) {
        /// The `id` column of the `policy` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `client_id` column of the `policy` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `role_id` column of the `policy` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        role_id -> Int8,
        /// The `name` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Varchar>,
        /// The `description` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `type` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "type"]
        type_ -> Nullable<Varchar>,
        /// The `invert_actions` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        invert_actions -> Nullable<Bool>,
        /// The `actions` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        actions -> Nullable<Array<Text>>,
        /// The `invert_resources` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        invert_resources -> Nullable<Bool>,
        /// The `resources` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        resources -> Nullable<Array<Text>>,
        /// The `invert_fields` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        invert_fields -> Nullable<Bool>,
        /// The `fields` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        fields -> Nullable<Array<Text>>,
        /// The `ip` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Array<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Nullable<Array<Text>>,
        /// The `mfa_required` column of the `policy` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        mfa_required -> Nullable<Bool>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `role` table.
    ///
    /// (Automatically generated by Diesel.)
    role (id) {
        /// The `id` column of the `role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `client_id` column of the `role` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `name` column of the `role` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `description` column of the `role` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `system_only` column of the `role` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        system_only -> Nullable<Bool>,
        /// The `archived` column of the `role` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        archived -> Nullable<Bool>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `session` table.
    ///
    /// (Automatically generated by Diesel.)
    session (id) {
        /// The `id` column of the `session` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `uid` column of the `session` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Varchar,
        /// The `client_id` column of the `session` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Int8,
        /// The `account_id` column of the `session` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        account_id -> Int8,
        /// The `mfa_state` column of the `session` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        mfa_state -> Varchar,
        /// The `access_token` column of the `session` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        access_token -> Nullable<Varchar>,
        /// The `refresh_token` column of the `session` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        refresh_token -> Nullable<Varchar>,
        /// The `signing_key` column of the `session` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        signing_key -> Varchar,
        /// The `created_at` column of the `session` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `last_activity_at` column of the `session` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        last_activity_at -> Nullable<Timestamp>,
        /// The `expires_at` column of the `session` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamp,
        /// The `user_agent` column of the `session` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        user_agent -> Nullable<Varchar>,
        /// The `ip` column of the `session` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Nullable<Varchar>,
    }
}

joinable!(account -> client (client_id));
joinable!(account -> role (role_id));
joinable!(account_access_history -> account (account_id));
joinable!(account_access_history -> client (client_id));
joinable!(account_pwd_history -> account (account_id));
joinable!(account_tokens -> account (account_id));
joinable!(audit_log -> client (client_id));
joinable!(policy -> client (client_id));
joinable!(policy -> role (role_id));
joinable!(role -> client (client_id));
joinable!(session -> account (account_id));
joinable!(session -> client (client_id));

allow_tables_to_appear_in_same_query!(
    account,
    account_access_history,
    account_pwd_history,
    account_tokens,
    audit_log,
    client,
    country,
    policy,
    role,
    session,
);
